// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetNews():Promise<Array<model.NewsSite>>;

export function Greet(arg1:string):Promise<string>;

export function Teste():Promise<model.News>;
